### ISSUE TITLE
正在使用 mkdocs ，发现几个问题想反馈一下

### ISSUE THREAD

**Issue by helperhaps** [upyun/docs#180]
首先，贵司使用 mkdocs 的方式给了我很大的启发，感谢。下面说问题

- mkdocs 版本
![screenshot_2017-05-15_04-18-53](https://cloud.githubusercontent.com/assets/8064048/26041572/69d936e2-391d-11e7-8a00-93b4834c1c07.png)
这是 v0.16 版升级所造成的，现在还是警告之后可能就直接报错了，2016-11-04 发布的 0.16 版本，差不多该升级了。

- 自适应支持
![screenshot_2017-05-15_04-31-02](https://cloud.githubusercontent.com/assets/8064048/26041768/1790ff08-391f-11e7-93df-a2e9460e7e01.png)
![screenshot_2017-05-15_04-32-02](https://cloud.githubusercontent.com/assets/8064048/26041771/19488e88-391f-11e7-973c-fa15dbc6c52a.png)
![screenshot_2017-05-15_04-32-38](https://cloud.githubusercontent.com/assets/8064048/26041772/1afb58d2-391f-11e7-889d-cf1d8d7c2028.png)
 
可以看到这是很难看的，其实这里有几个方案，1. 完全不支持自适应，设置页面最小宽度，然后设备宽度小于最小宽度使用底部滚动条，这个是最简单易用的并且小屏幕看文档的需求本来就不多 2. 就是要支持了，这可能会比较麻烦。

现在的状况是最顶部的导航条还算自适应，底部也还可以，但是左侧侧边导航就完全不行了，另外图片会撑大整个页面，IPad 视角更是不行，见上图

- hackDOM 的使用
个人是比较喜欢使用 css 的，即能用 css 解决绝不使用 js。
这里是对 index 页和 download 页做特殊处理，但其实可以完全不用 js 就可以达到相同的效果（index 页我已经试过了，download 可能稍微麻烦一点）

最后，我很乐于贡献自己的代码来解决上述问题（是我擅自认为是问题），当然，这也要在你们作出决定之后。

**Comment by huangnauh** [comment]
欢迎提 pr

**Comment by helperhaps** [comment]
我不是这个意思，

比如，mkdocs 版本问题，要不要升级呢？
自适应要怎么考虑呢？
hackDOM 到底是用不用呢？

这些问题要等你们决定之后，回答之后，再开始做，不然没啥方向啊，

**Comment by sabakugaara** [comment]
- [ ] upgrade mkdocs

应该会先考虑升级版本

**Comment by helperhaps** [comment]
@sabakugaara 

- [x] upgrade mkdocs to v0.16  by https://github.com/upyun/docs/pull/183.

**Comment by helperhaps** [comment]
看样子其他的问题貌似不是什么问题，那这个 issue 我就关了
