### ISSUE TITLE
新旧表单 API 密钥替换时，旧的表单 API 密钥的保留生效时间说明

### ISSUE THREAD

**Issue by kaidiren** [upyun/docs#33]
因为在 console.upyun.com 的服务里可以随时更新表单 API 密钥。当表单 API 密钥更新时，如果还有旧的密钥在访问，是否可以访问？ 如果可以访问有效期保留的是多久？这些都还没在文档里说明。希望能补充一下。

**Comment by polym** [comment]
ping @timebug

**Comment by kaidiren** [comment]
啊，记错了是 token 防盗链的特性
