### ISSUE TITLE
为什么文档上说签名的有效期为30分钟，

### ISSUE THREAD

**Issue by hzl7652** [upyun/docs#4]
注: 签名的有效期为 30 分钟。如果超过 30 分钟，则需重新生成签名。
我看相应的文档，我想不通签名加上有效期的意义何在，因为每次请求的时间都不一样的？

**Comment by timebug** [comment]
有效时间是为了约束 token 的作用周期。如果去掉时间约束，那么一旦 token 被其他人知道，他就可以一直用这串 token 进行签名，反之，这串 token 只能在一定时间内有效，过期就无效了。

**Comment by hzl7652** [comment]
token设置了有效期，是不是你们在后面要记录过所有生成的token

**Comment by oneoo** [comment]
token 中带有过期时间的
