### ISSUE TITLE
异步音视频处理文档中的MD5计算疑似有误

### ISSUE THREAD

**Issue by BlackGlory** [upyun/docs#52]
[异步音视频处理](http://docs.upyun.com/cloud/av/#_4)里提到

> 连接操作员名和进行 md5 计算之后的操作员密码：
>     `operator_testerbucket_nameimtesternotify_urlhttp://www.example.com/notify/source/video/20130514_190031.mp4tasksW3sidHlwZSI6InZpZGVvIiwiYml0cmF0ZSI6IjUwMCIsInJvdGF0ZSI6ImF1dG8iLCJmb3JtYXQiOiJtcDQifSx7InR5cGUiOiJ0aHVtYm5haWwiLCJ0aHVtYl9zaWdubGUiOmZhbHNlLCJ0aHVtYl9hbW91bnQiOjEwMCwiZm9ybWF0IjoicG5nIn1d97b5a9d718b7a2064f7e7673c4d8bcb8`
> 
> 将得到的字符串进行 md5 计算, 得到最终的 `signature` 值为 `ad91a9ab81ecc34e973844a6723ce354`.

# MD5转换的结果:

在线MD5网站的计算结果`e801eeb40d8e2160c266c94d6fc2ba3f`
官方提供的Node.js SDK中md5sum的计算结果 `e801eeb40d8e2160c266c94d6fc2ba3f`
通过Node.js的module iconv-lite转换utf8后再md5sum的计算结果 `e801eeb40d8e2160c266c94d6fc2ba3f`

文档是否有误?

我自己通过文档给出的计算方法调用[异步文件拉取](http://docs.upyun.com/cloud/spider/)时, 也提示`signature error`, 是文档不对还是我理解有偏差?

**Comment by polym** [comment]
文档的确有问题，我们这边会重新调整案例。请问，在文件拉取签名计算过程中，有将 `app_name` 作为计算签名的算子么？

**Comment by BlackGlory** [comment]
@polym 当前的文档里写明了

>授权认证的方法与异步音视频处理授权认证方法完全一致, 具体可参考 [授权认证](http://docs.upyun.com/cloud/av/#_4).

>`signature` 参数通过下面的方式获得：

>1\. 将参数按照参数名称的字典顺序排序后, 将参数键值对连接成一个字符串.

所以是有将app_name作为计算签名的算子的, 我刚刚重新检查了一下自己的代码, 发现出现signature error是因为没有按字典顺序排序, 现在已经可以跑通了. 建议把文档里curl命令和表格里的参数都按字典顺序排序, 避免类似的问题发生.

**Comment by polym** [comment]
![image](https://cloud.githubusercontent.com/assets/2860926/15992013/b1f3fb74-30f4-11e6-8eae-43253916f81f.png)
