### ISSUE TITLE
what could i do with errorCode:42900001

### ISSUE THREAD

**Issue by cdll** [upyun/docs#58]
使用nodeSDK上传文件夹（貌似文件有点多），返回了错误``statusCode: 429; body: {"msg":"too many requests","code":42900001,"id":"87667a942631f57e748d741b15ebdd5e"}``，话说这个问题有什么解决方案么？
求助，谢谢~

**Comment by yejingx** [comment]
放慢上传频率，比如上传一个文件后 sleep 一下。
另外，这里是文档仓库，node sdk 问题请前往：https://github.com/upyun/node-sdk/issues
谢谢。

**Comment by yejingx** [comment]
放慢上传频率，比如上传一个文件后 sleep 一下。
另外，这里是文档仓库，node sdk 问题请前往：https://github.com/upyun/node-sdk/issues
谢谢。
